### PR TITLE
Added UMD

### PR DESCRIPTION
**Pull request by dev101**

### CODE REVIEW

**Comment by xonixx** [comment]
The problem with this change is that it doesn't define `window.jsqry` anymore.
So, you can't run SpecRunner.html now.
Could we please fix this?

**Comment by xonixx** [comment]
Then, other small issue. You've removed `undefined` from parameter, so now it's possible to redefine it globally & hence break the lib.

**Comment by dev101** [comment]
Improved in #7

**Comment by xonixx** [comment]
Thanks, will check later today.

**Pull request closed without merging**
